_target_: src.datamodules.plant_datamodule.PlantModule

data_dir: /nfs2/personal/cmpark/dacon/dataset/train/ # data_dir is specified in config.yaml
test_data_dir : /nfs2/personal/cmpark/dacon/dataset/test/
batch_size: 100
num_workers: 4
pin_memory: False
crop: False
fold: 0 # 0~4
label_type : total # total,binary,positive,negative
train_augmentation_list: 
  - _target_: albumentations.HueSaturationValue
    always_apply: false
    hue_shift_limit: 0.2
    p: 0.5
  - _target_: albumentations.RandomBrightnessContrast
    brightness_limit: 0.2
    contrast_limit: 0.2
    p: 0.5
  - _target_: albumentations.RandomCrop
    always_apply: true
    height: 256
    width: 256
    p: 1.0
  - _target_: albumentations.Flip
    always_apply: true
  - _target_: albumentations.Normalize
    p: 1.0
  - _target_: albumentations.pytorch.transforms.ToTensorV2
    always_apply: true
valid_augmentation_list: 
  - _target_: albumentations.Normalize
    p: 1.0
  - _target_: albumentations.pytorch.transforms.ToTensorV2
    always_apply: true


